server:
  port: 18080

spring:
  application:
    name: file-upload-function
  servlet:
    multipart:
      # 开启文件上传
      enabled: true
      # 最大请求大小
      max-request-size: 20MB
      # 最大文件大小
      max-file-size: 20MB
      # 文件位置
      # location: